- name: Play 01 - Create droplets and define hosts
  hosts: main
  vars_files: 
    - /home/main/env/env.yml
  vars:
    api_token: "{{ env.DO_TOKEN }}"
    domain: "{{ env.DOMAIN }}"
    host_user: "{{ env.HOST_USER_NAME }}"
    host_pass: "{{ env.HOST_USER_PASS }}"
    host_ssh_public_key: "{{ env.SSH_PUBLIC_KEY }}"
    hosts_file: "{{ env.HOSTS_FILE }}"
    host_vars: 
      domain: "{{ domain }}"
      host_user: "{{ host_user }}"
      host_pass: "{{ host_pass }}"
      host_ssh_public_key: "{{ host_ssh_public_key }}"
    host_user_data: "{{ lookup('template', 'user_data.j2', template_vars=dict(host_vars)) | trim }}"
    do_tags:      
    - host
    - test-do
    droplets:
    - { id: '001', name: 'kube-001', state: present }
    # - { id: '002', name: 'kube-002', state: present }
    # - { id: '003', name: 'kube-003', state: deleted }
  tasks:
  - name: verify if variables are defined
    fail: 
      msg: "Variable '{{ item.name }}' is not defined"
    when: item.value is undefined or item.value == ""
    with_items:
    - { name: "api_token", value: "{{ api_token }}"}
    - { name: "domain", value: "{{ domain }}"}
    - { name: "host_user", value: "{{ host_user }}"}
    - { name: "host_pass", value: "{{ host_pass }}"}
    - { name: "host_user", value: "{{ host_user }}"}
    - { name: "host_ssh_public_key", value: "{{ host_ssh_public_key }}"}
    - { name: "host_user_data", value: "{{ host_user_data }}"}
    loop_control:
      label: "{{ item.name }}"
      
  - name: create tags
    digital_ocean_tag:
      api_token: "{{ api_token }}"
      name: "{{ item }}"
      state: present
    with_items:
    - "{{ do_tags }}"

  - name: create droplets
    digital_ocean:
      api_token: "{{ api_token }}"
      id: "{{ item.id }}"
      name: "{{ item.name }}"
      unique_name: yes
      state: "{{ item.state }}"
      command: droplet
      size_id: 1gb
      region_id: nyc1
      image_id: ubuntu-18-04-x64
      private_networking: yes
      ipv6 : yes
      user_data: "{{ host_user_data }}"
      wait_timeout: 500
    with_items:
    - "{{ droplets }}"
    loop_control:
      label: "{{ item.name }}"
    register: droplet_details

  - debug: msg="IP of droplet {{ item.droplet.name }} is {{ item.droplet.ip_address }}"
    with_items: 
    - "{{ droplet_details.results }}"
    loop_control:
      label: "{{ item.droplet.name }}"

  # - name: add hosts
  #   add_host: 
  #     name: "{{ item.droplet.ip_address }}"
  #     group: "masters"
  #   with_items: 
  #   - "{{ droplet_details.results }}"
  #   loop_control:
  #     label: "{{ item.droplet.name }}"

  - name: tag each droplet
    digital_ocean_tag:
      api_token: "{{ api_token }}"
      resource_id: "{{ item[0].droplet.id }}"
      name: "{{ item[1] }}"
      state: present
    with_nested:
    - "{{ droplet_details.results }}"
    - "{{ do_tags }}"
    loop_control:
      label: "droplet: {{ item[0].droplet.name }} - tag: {{ item[1] }}"

  - name: Generate hosts to populate the hosts file
    set_fact: 
      masters: |
        {{ masters }}
        {{ item.droplet.name }} ansible_host={{ item.droplet.ip_address }} ansible_user={{ host_user }} ansible_become_pass={{ host_pass }}
    with_items: 
    - "{{ droplet_details.results }}"
    loop_control:
      label: "{{ item.droplet.name }}"

  - debug: msg="masters='{{ masters }}'"

  - name: Update the hosts file with the generated hosts
    blockinfile:
      path: "{{ hosts_file }}"
      marker: "# {mark} ANSIBLE MANAGED BLOCK - MASTERS"
      insertafter: "[masters]"
      block: {{ masters }}

    - name: refresh inventory
      meta: refresh_inventory

  # - name: create a domain record for each corresponding droplet
  #   digital_ocean_domain:
  #     api_token: "{{ api_token }}"
  #     state: present
  #     name: "{{ item.droplet.name }}.internal.{{ domain }}"
  #     ip: "{{ item.droplet.ip_address }}"
  #   with_items:
  #   - "{{ droplet_details.results }}"
  #   loop_control:
  #     label: "{{ item.droplet.name }}"

- name: Play 02 - Update configuration
  hosts: masters
  tasks:
  - name: print last line of setup.log
    shell: tail -n 1 /home/host/setup.log
    register: setup_finished

  - debug: msg="setup_finished='{{ setup_finished }}'"
    
  - name: verify if the setup was finished successfully
    fail: 
      msg: "Variable '{{ setup_finished }}' should be equal to 'Setup Finished'"
    when: setup_finished != "Setup Finished"