- hosts: digitalocean
  tasks:
  - name: create tags
    digital_ocean_tag:
      api_token: "{{ lookup('env', 'DO_TOKEN') }}"
      name: "{{ item }}"
      state: present
    with_items:
      - host
      - test-do

  - digital_ocean:
      api_token: "{{ lookup('env', 'DO_TOKEN') }}"
      state: present
      command: droplet
      name: testhost
      size_id: 1gb
      region_id: nyc1
      image_id: ubuntu-18-04-x64
      private_networking: yes
      ipv6 : yes
      user_data: "{{ lookup('template', 'user_data.j2') | trim }}"
      wait_timeout: 500
    register: testhost

  - debug:
      msg: "ID is {{ testhost.droplet.id }}"

  - debug:
      msg: "IP is {{ testhost.droplet.ip_address }}"

  - name: tag a resource; creating the tag if it does not exist
    digital_ocean_tag:
      api_token: "{{ lookup('env', 'DO_TOKEN') }}"
      name: "{{ item }}"
      resource_id: "{{ testhost.droplet.id }}"
      state: present
    with_items:
      - host
      - test-do