- name: Play 01 - Verify if variables are defined
  hosts: main
  vars_files: 
    - /home/main/env/env.yml
  vars:
    general:
      hosts_file: "/home/main/ansible/hosts"
      log_file: "/var/log/setup.log"
      setup_last_line: "Setup Finished"
      droplet_state: "present"
      api_token: "{{ env.DO_TOKEN }}"
      host_user: "{{ env.HOST_USER_NAME }}"
      host_pass: "{{ env.HOST_USER_PASS }}"
      host_ssh_public_key: "{{ env.SSH_PUBLIC_KEY }}"
      host_vars: 
        host_user: "{{ general.host_user }}"
        host_pass: "{{ general.host_pass }}"
        host_ssh_public_key: "{{ general.host_ssh_public_key }}"
      main_region_id: nyc1
      main_droplet_info:
        image_id: ubuntu-18-04-x64
        size_id: 1gb
        private_networking: yes
        ipv6: yes
        wait_timeout: 500
      master_user_data: "{{ lookup('template', 'user_data.master.j2', template_vars=dict(general.host_vars)) | trim }}"
      worker_user_data: "{{ lookup('template', 'user_data.worker.j2', template_vars=dict(general.host_vars)) | trim }}"
    masters:
      hosts_group: 'masters'
      hosts_file: "{{ general.hosts_file }}"
      api_token: "{{ general.api_token }}"
      host_user: "{{ general.host_user }}"
      host_pass: "{{ general.host_pass }}"
      droplet_info:
        image_id: "{{ general.main_droplet_info.image_id }}"
        size_id: "{{ general.main_droplet_info.size_id }}"
        private_networking: "{{ general.main_droplet_info.private_networking }}"
        ipv6: "{{ general.main_droplet_info.ipv6 }}"
        wait_timeout: "{{ general.main_droplet_info.wait_timeout }}"
        user_data: "{{ general.master_user_data }}"
      do_tags:      
      - host
      - kube
      droplets:
      - { name: 'kube-001', region_id: "{{ general.main_region_id }}", state: "{{ general.droplet_state }}" }
    workers:
      hosts_group: 'workers'
      hosts_file: "{{ general.hosts_file }}"
      api_token: "{{ general.api_token }}"
      host_user: "{{ general.host_user }}"
      host_pass: "{{ general.host_pass }}"
      droplet_info:
        image_id: "{{ general.main_droplet_info.image_id }}"
        size_id: "{{ general.main_droplet_info.size_id }}"
        private_networking: "{{ general.main_droplet_info.private_networking }}"
        ipv6: "{{ general.main_droplet_info.ipv6 }}"
        wait_timeout: "{{ general.main_droplet_info.wait_timeout }}"
        user_data: "{{ general.worker_user_data }}"
      do_tags:      
      - host
      - worker
      droplets:
      - { name: 'worker-001', region_id: "{{ general.main_region_id }}", state: "{{ general.droplet_state }}" }
      - { name: 'worker-002', region_id: "{{ general.main_region_id }}", state: "{{ general.droplet_state }}" }
      - { name: 'worker-003', region_id: "{{ general.main_region_id }}", state: "{{ general.droplet_state }}" }
  roles:
  - role: validation
    api_token: "{{ general.api_token }}"
    host_user: "{{ general.host_user }}"
    host_pass: "{{ general.host_pass }}"
    host_ssh_public_key: "{{ general.host_ssh_public_key }}"
    master_user_data: "{{ general.master_user_data }}"
    worker_user_data: "{{ general.worker_user_data }}"
  
  - role: droplets
    hosts_file: "{{ masters.hosts_file }}"
    api_token: "{{ masters.api_token }}"
    host_user: "{{ masters.host_user }}"
    host_pass: "{{ masters.host_pass }}"
    hosts_group: "{{ masters.hosts_group }}"
    droplet_info: "{{ masters.droplet_info }}"
    do_tags: "{{ masters.do_tags }}"
    droplets: "{{ masters.droplets }}"
  
  - role: droplets
    hosts_file: "{{ workers.hosts_file }}"
    api_token: "{{ workers.api_token }}"
    host_user: "{{ workers.host_user }}"
    host_pass: "{{ workers.host_pass }}"
    hosts_group: "{{ workers.hosts_group }}"
    droplet_info: "{{ workers.droplet_info }}"
    do_tags: "{{ workers.do_tags }}"
    droplets: "{{ workers.droplets }}"

  - role: test
    log_file: "{{ general.log_file }}"
    setup_last_line: "{{ general.setup_last_line }}"
    initial_connection_timeout: 60
    setup_finished_timeout: 60