- name: Play 01 - Reset the cluster
  hosts: masters
  vars_files: 
    - /home/main/env/env.yml
  vars:
    main: "{{ env }}"
  tasks:
  - name: create /var/log/kube directory
    become: true
    file:
      path: "/var/log/kube"
      state: directory
      mode: 0755
      owner: "{{ main.host_user }}"

  - name: reset the cluster
    become: true
    shell: kubeadm reset -f >> /var/log/kube/reset.log

  - name: delete the /home/{{ main.host_user }}/.kube directory
    become: true
    file:
      path: "/home/{{ main.host_user }}/.kube"
      state: absent