- name: Play 05 - Prepare the cluster
  hosts: masters
  vars_files: 
    - /home/main/env/env.yml
  vars:
    main: "{{ env }}"
  roles:
  - role: cluster
    host_user: "{{ main.host_user }}"
    kube_network_directory: "{{ main.kube_network_directory }}"
    kube_network_file: "{{ main.kube_network_file }}"
    kube_etcd_endpoints: "{{ main.kube_etcd_endpoints }}"
    pod_cidr: "{{ main.pod_cidr }}"
    kubeadm_init_params: "{{ main.kubeadm_init_params }}"
  
  - role: kube-run
    host_user: "{{ main.host_user }}"

###############################################################################

- name: Play 06 - Join the cluster
  hosts: workers
  vars_files: 
    - /home/main/env/env.yml
  vars:
    main: "{{ env }}"
  roles:
  - role: kube-run
    host_user: "{{ main.host_user }}"
