- name: check if the file "/home/{{ host_user }}/.tmp/deploy" exists
  stat:
    path: "/home/{{ host_user }}/.tmp/deploy"
  register: tmp_file
  
- set_fact:
    run_tasks: "{{ (tmp_file is not defined) or (tmp_file.stat.exists == False) }}"

- name: create the deployment
  shell: kubectl create deployment {{ deployment_name }} --image {{ image }}
  when: run_tasks

- name: expose the deployment
  shell: kubectl expose deployment {{ deployment_name }} --type={{ type }} --port {{ my_port }} --target-port {{ target_port }}
  when: run_tasks

- name: create the /home/{{ host_user }}/.tmp directory
  file:
    path: "/home/{{ host_user }}/.tmp"
    state: directory
  when: run_tasks

- name: create the /home/{{ host_user }}/.tmp/deploy file
  copy:
    content: ""
    dest: "/home/{{ host_user }}/.tmp/deploy"
    force: no
    mode: 0644
  when: run_tasks