- name: create the deployment
  shell: kubectl create deployment my-nginx --image nginx

- name: expose the deployment
  shell: kubectl expose deployment my-nginx --type=LoadBalancer --port 80 --target-port 80 --node-port 31000