- name: create the deployment
  shell: kubectl create deployment my-deployment --image {{ image }}

- name: expose the deployment
  shell: kubectl expose deployment my-deployment --type={{ type }} --port {{ port }} --target-port {{ targetPort }} --node-port {{ nodePort }}