- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw
  when: "'masters' in group_names"

- name: set join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"
  when: "'masters' in group_names"

- name: TCP port 6443 on master is reachable from worker
  wait_for: "host={{ hostvars[groups['masters'][0]]['ansible_default_ipv4']['address'] }} port=6443 timeout=1"
  when: "'workers' in group_names"

- name: join cluster
  shell: "{{ hostvars[groups['masters'][0]].join_command }} >> node_joined.txt"
  args:
    chdir: $HOME
    creates: node_joined.txt
  when: "'workers' in group_names"