- name: check file "/home/{{host_user}}/.kube/config" exists
  stat:
    path: /etc/issue
  register: tmp_file
  
- set_fact:
    run_tasks: tmp_file.stat.exists == False
  
- name: initialize the cluster
  become: yes
  become_user: "{{host_user}}"
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt
  when: run_tasks

- name: create .kube directory
  become: yes
  become_user: "{{host_user}}"
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755
  when: run_tasks

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{host_user}}/.kube/config"
    remote_src: yes
    owner: "{{host_user}}"
  when: run_tasks

- name: copy admin.conf to root's kube config
  copy:
    src: "/home/{{host_user}}/.kube/config"
    dest: "/root/.kube/config"
    remote_src: yes
    owner: "root"

- name: install Pod network
  become: yes
  become_user: "{{host_user}}"
  shell: kubectl apply --filename https://git.io/weave-kube-1.6 >> pod_network_setup.txt
  #shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml >> pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt