- name: check file "/home/{{ host_user }}/.kube/config" exists
  stat:
    path: "/home/{{ host_user }}/.kube/config"
  register: tmp_file
  
- set_fact:
    run_tasks: "{{ (tmp_file is not defined) or (tmp_file.stat.exists == False) }}"

- name: create /var/log/kube directory
  become: true
  # become_user: "{{ host_user }}"
  file:
    path: "/var/log/kube"
    state: directory
    mode: 0755
    owner: "{{ host_user }}"
  
- name: initialize the cluster
  become: true
  # become_user: "{{ host_user }}"
  shell: kubeadm init {{ kubeadm_init_params | default('') }} >> /var/log/kube/cluster_initialized.log
  when: run_tasks

- name: create .kube directory
  become: true
  file:
    path: "/home/{{ host_user }}/.kube"
    state: directory
    mode: 0755
    owner: "{{ host_user }}"
  when: run_tasks

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ host_user }}/.kube/config"
    remote_src: yes
    owner: "{{ host_user }}"
  when: run_tasks

- name: Creates the "/home/{{ host_user }}/tmp" directory
  file:
    path: "/home/{{ host_user }}/tmp"
    state: directory

- name: copy the local template file "data/{{ kube_network_file }}" to host
  template:
    src: "{{ kube_network_directory }}/{{ kube_network_file }}"
    dest: "/home/{{ host_user }}/tmp/{{ kube_network_file }}"
    mode: 0644
    owner: "{{ host_user }}"
  vars: 
    kube_etcd_endpoints: "{{ kube_etcd_endpoints }}"
    pod_cidr: "{{ pod_cidr }}"

- name: install Pod network
  shell: kubectl apply --timeout 120s --filename "/home/{{ host_user }}/tmp/{{ kube_network_file }}" >> /var/log/kube/pod_network_setup.log